### ISSUE TITLE
페이지 라우팅

### ISSUE THREAD

**Issue by frombozztoang** [MJU-Letter/Web#7]
## 💌 **이슈 설명**

각 도메인 별 페이지 라우팅

## 📬 **상세 작업 내용**

- [x] layout GNB 
- [x] 메인화면
- [x] 로그인
- [x] 검색
- [x] 알림
- [x] 마이페이지 
- [x] 설정

**Comment by EunbeenDev** [comment]
우와 소통해요

**Comment by frombozztoang** [comment]
> 이슈 내가 닫을 뻔

나빠요

> 우와 소통해요

안녕하세요
